INSERT INTO Category VALUES (0, 'STANDARD');
INSERT INTO Category VALUES (1, 'PREMIUM');
INSERT INTO Category VALUES (2, 'BAR');

INSERT INTO User VALUES ('admin', 'admin');
INSERT INTO User VALUES ('user', 'user');


INSERT INTO Ticket VALUES (DEFAULT, 'Saw 1', '2013-10-01', 0, 12, 'admin');
INSERT INTO Ticket VALUES (DEFAULT, 'Saw 2', '2013-10-03', 0, 1, DEFAULT);
INSERT INTO Ticket VALUES (DEFAULT, 'Saw 3', '2013-10-04', 2, 6, DEFAULT);
INSERT INTO Ticket VALUES (DEFAULT, 'Saw 4', '2013-10-03', 1, 5, DEFAULT);



